# C_SOURCES += $(wildcard lib/STM8S_StdPeriph_Driver/src/*.c)

# C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_adc1.c
# # C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_adc2.c
# C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_awu.c
# C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_beep.c
# # C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_can.c
# C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_clk.c
# C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_exti.c
# C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_flash.c
C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_gpio.c
# C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_i2c.c
# C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_itc.c
# C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_iwdg.c
# C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_rst.c
# C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_spi.c
# C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_tim1.c
# C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_tim2.c
# # C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_tim3.c
# C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_tim4.c
# # C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_tim5.c
# # C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_tim6.c
# C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_uart1.c
# # C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_uart2.c
# # C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_uart3.c
# # C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_uart4.c
# C_SOURCES += lib/STM8S_StdPeriph_Driver/src/stm8s_wwdg.c

C_INCLUDES += \
	-I lib/STM8S_StdPeriph_Driver/inc/ \
	-I lib/STM8S_StdPeriph_Driver/ 