# C_SOURCES += $(wildcard lib/STM8S_StdPeriph_Driver/src/*.c)
C_SOURCES += \
	lib/STM8S_StdPeriph_Driver/src/stm8s_adc1.c \
	lib/STM8S_StdPeriph_Driver/src/stm8s_awu.c \
	lib/STM8S_StdPeriph_Driver/src/stm8s_beep.c \
	lib/STM8S_StdPeriph_Driver/src/stm8s_clk.c \
	lib/STM8S_StdPeriph_Driver/src/stm8s_exti.c \
	lib/STM8S_StdPeriph_Driver/src/stm8s_flash.c \
	lib/STM8S_StdPeriph_Driver/src/stm8s_gpio.c \
	lib/STM8S_StdPeriph_Driver/src/stm8s_i2c.c \
	lib/STM8S_StdPeriph_Driver/src/stm8s_itc.c \
	lib/STM8S_StdPeriph_Driver/src/stm8s_iwdg.c \
	lib/STM8S_StdPeriph_Driver/src/stm8s_rst.c \
	lib/STM8S_StdPeriph_Driver/src/stm8s_spi.c \
	lib/STM8S_StdPeriph_Driver/src/stm8s_tim1.c \
	lib/STM8S_StdPeriph_Driver/src/stm8s_tim2.c \
	lib/STM8S_StdPeriph_Driver/src/stm8s_tim4.c \
	lib/STM8S_StdPeriph_Driver/src/stm8s_uart1.c \
	lib/STM8S_StdPeriph_Driver/src/stm8s_wwdg.c \

C_INCLUDES += \
	-I lib/STM8S_StdPeriph_Driver/inc/ \
	-I lib/STM8S_StdPeriph_Driver/ 